### ISSUE TITLE
trying to use libconsole_bridge.so.0.4, should use libconsole_bridge.so.1.0 or libconsole_bridge.so

### ISSUE THREAD

**Issue by thearthur** [ros-melodic-arch/ros-melodic-rviz#11]
sorry if this is not the right place to seek help on this, the[ AUR package here](https://aur.archlinux.org/packages/ros-melodic-rviz): pointed to this repo

the AUR package fail to build with this:
```
make[2]: *** No rule to make target '/usr/lib/libconsole_bridge.so.0.4', needed by 'devel/lib/librviz.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:2873: src/rviz/CMakeFiles/rviz.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by bionade24** [comment]
One or more dependencies in your system are linked against the old version of console_bridge. Rebuild  the deps or use my repo.

**Comment by acxz** [comment]
@thearthur if you are using `yay`. Run the following command to rebuild your deps: `yay -Syu ros-melodic-rviz --rebuildtree`.
